export const FIREBASE_ADMIN_TYPE = process.env.FIREBASE_ADMIN_TYPE
export const FIREBASE_ADMIN_PROJECT_ID = process.env.FIREBASE_ADMIN_PROJECT_ID
export const FIREBASE_ADMIN_PRIVATE_KEY_ID =
  process.env.FIREBASE_ADMIN_PRIVATE_KEY_ID
export const FIREBASE_ADMIN_PRIVATE_KEY = process.env.FIREBASE_ADMIN_PRIVATE_KEY
export const FIREBASE_ADMIN_CLIENT_EMAIL =
  process.env.FIREBASE_ADMIN_CLIENT_EMAIL
export const FIREBASE_ADMIN_CLIENT_ID = process.env.FIREBASE_ADMIN_CLIENT_ID
export const FIREBASE_ADMIN_AUTH_URI = process.env.FIREBASE_ADMIN_AUTH_URI
export const FIREBASE_ADMIN_TOKEN_URI = process.env.FIREBASE_ADMIN_TOKEN_URI
export const FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL =
  process.env.FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL
export const FIREBASE_ADMIN_CLIENT_X509_CERT_URL =
  process.env.FIREBASE_ADMIN_CLIENT_X509_CERT_URL
